# Generated by Django 3.1.5 on 2021-02-02 02:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auction_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=64)),
                ('img_url', models.CharField(blank=True, max_length=512, null=True)),
                ('active_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='member_since',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='bids',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auction_listing_id', serialize=False, to='auctions.auction_listing')),
                ('bid', models.DecimalField(decimal_places=2, max_digits=17)),
                ('last_bid_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
