# Generated by Django 3.1.5 on 2021-02-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210204_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='starting_bid',
            new_name='highest_bid',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='bid_author',
            new_name='highest_bid_user',
        ),
        migrations.RemoveField(
            model_name='bids',
            name='bid',
        ),
    ]
