# Generated by Django 3.1.5 on 2021-02-05 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210205_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction_listing',
            old_name='highest_bid',
            new_name='starting_bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='highest_bid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17),
        ),
    ]
