# Generated by Django 3.1.5 on 2021-02-09 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210205_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction_listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('BM', 'Books, Moves & Music'), ('EL', 'Electronics'), ('CO', 'Collectibles & Art'), ('HG', 'Home & Garden'), ('SG', 'Sporting Goods'), ('TH', 'Toys & Hobbies'), ('BI', 'Business & Industrial'), ('HB', 'Health & Beauty'), ('OT', 'Others')], default='OT', help_text='If not specified it will be set as Others', max_length=2),
        ),
        migrations.AlterField(
            model_name='auction_listing',
            name='img_url',
            field=models.CharField(blank=True, help_text='Optional', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.auction_listing'),
        ),
    ]
