# Generated by Django 3.1.5 on 2021-02-09 02:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210208_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listing',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='user_watchlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
